// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

using Enterprise.Platform.Contracts.DTOs.EventShopper;
using Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities;
using Mapster;

namespace Enterprise.Platform.Infrastructure.Persistence.EventShopper.Mappings;

/// <summary>Mapster registry auto-generated by DtoGen. One entry per scaffolded entity; bi-directional bindings.</summary>
public sealed class EventShopperMappingRegistry : IRegister
{
    /// <inheritdoc />
    public void Register(TypeAdapterConfig config)
    {
        ArgumentNullException.ThrowIfNull(config);

        config.NewConfig<AiPreviews, AiPreviewsDto>();
        config.NewConfig<AiPreviewsDto, AiPreviews>();
        config.NewConfig<Appointments, AppointmentsDto>();
        config.NewConfig<AppointmentsDto, Appointments>();
        config.NewConfig<AuditLogs, AuditLogsDto>();
        config.NewConfig<AuditLogsDto, AuditLogs>();
        config.NewConfig<ChatMessages, ChatMessagesDto>();
        config.NewConfig<ChatMessagesDto, ChatMessages>();
        config.NewConfig<ChatSessions, ChatSessionsDto>();
        config.NewConfig<ChatSessionsDto, ChatSessions>();
        config.NewConfig<CustomerProfiles, CustomerProfilesDto>();
        config.NewConfig<CustomerProfilesDto, CustomerProfiles>();
        config.NewConfig<Events, EventsDto>();
        config.NewConfig<EventsDto, Events>();
        config.NewConfig<FamilyMembers, FamilyMembersDto>();
        config.NewConfig<FamilyMembersDto, FamilyMembers>();
        config.NewConfig<FulfillmentOrders, FulfillmentOrdersDto>();
        config.NewConfig<FulfillmentOrdersDto, FulfillmentOrders>();
        config.NewConfig<GarmentMeasurementMaps, GarmentMeasurementMapsDto>();
        config.NewConfig<GarmentMeasurementMapsDto, GarmentMeasurementMaps>();
        config.NewConfig<Garments, GarmentsDto>();
        config.NewConfig<GarmentsDto, Garments>();
        config.NewConfig<Guests, GuestsDto>();
        config.NewConfig<GuestsDto, Guests>();
        config.NewConfig<JobCardStageLogs, JobCardStageLogsDto>();
        config.NewConfig<JobCardStageLogsDto, JobCardStageLogs>();
        config.NewConfig<JobCards, JobCardsDto>();
        config.NewConfig<JobCardsDto, JobCards>();
        config.NewConfig<MeasurementAttributes, MeasurementAttributesDto>();
        config.NewConfig<MeasurementAttributesDto, MeasurementAttributes>();
        config.NewConfig<MemberMeasurements, MemberMeasurementsDto>();
        config.NewConfig<MemberMeasurementsDto, MemberMeasurements>();
        config.NewConfig<OrderMilestones, OrderMilestonesDto>();
        config.NewConfig<OrderMilestonesDto, OrderMilestones>();
        config.NewConfig<Orders, OrdersDto>();
        config.NewConfig<OrdersDto, Orders>();
        config.NewConfig<OtpEntries, OtpEntriesDto>();
        config.NewConfig<OtpEntriesDto, OtpEntries>();
        config.NewConfig<OutboxMessages, OutboxMessagesDto>();
        config.NewConfig<OutboxMessagesDto, OutboxMessages>();
        config.NewConfig<Payments, PaymentsDto>();
        config.NewConfig<PaymentsDto, Payments>();
        config.NewConfig<Permissions, PermissionsDto>();
        config.NewConfig<PermissionsDto, Permissions>();
        config.NewConfig<ProductionRequestStageLogs, ProductionRequestStageLogsDto>();
        config.NewConfig<ProductionRequestStageLogsDto, ProductionRequestStageLogs>();
        config.NewConfig<ProductionRequests, ProductionRequestsDto>();
        config.NewConfig<ProductionRequestsDto, ProductionRequests>();
        config.NewConfig<PromoCodes, PromoCodesDto>();
        config.NewConfig<PromoCodesDto, PromoCodes>();
        config.NewConfig<Referrals, ReferralsDto>();
        config.NewConfig<ReferralsDto, Referrals>();
        config.NewConfig<RefreshTokens, RefreshTokensDto>();
        config.NewConfig<RefreshTokensDto, RefreshTokens>();
        config.NewConfig<Reviews, ReviewsDto>();
        config.NewConfig<ReviewsDto, Reviews>();
        config.NewConfig<RolePermissions, RolePermissionsDto>();
        config.NewConfig<RolePermissionsDto, RolePermissions>();
        config.NewConfig<Roles, RolesDto>();
        config.NewConfig<RolesDto, Roles>();
        config.NewConfig<ScreenMappings, ScreenMappingsDto>();
        config.NewConfig<ScreenMappingsDto, ScreenMappings>();
        config.NewConfig<Sessions, SessionsDto>();
        config.NewConfig<SessionsDto, Sessions>();
        config.NewConfig<SystemCategories, SystemCategoriesDto>();
        config.NewConfig<SystemCategoriesDto, SystemCategories>();
        config.NewConfig<SystemCodes, SystemCodesDto>();
        config.NewConfig<SystemCodesDto, SystemCodes>();
        config.NewConfig<SystemSettings, SystemSettingsDto>();
        config.NewConfig<SystemSettingsDto, SystemSettings>();
        config.NewConfig<UserPasswordHistory, UserPasswordHistoryDto>();
        config.NewConfig<UserPasswordHistoryDto, UserPasswordHistory>();
        config.NewConfig<UserRoles, UserRolesDto>();
        config.NewConfig<UserRolesDto, UserRoles>();
        config.NewConfig<Users, UsersDto>();
        config.NewConfig<UsersDto, Users>();
        config.NewConfig<VehicleLocations, VehicleLocationsDto>();
        config.NewConfig<VehicleLocationsDto, VehicleLocations>();
    }
}
