// <auto-generated>
//     This file was emitted by tools/Enterprise.Platform.DtoGen.
//     Do not edit by hand — changes will be overwritten on the next regen.
//     For custom mapping logic, add a sibling partial in the same namespace.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.App;

/// <summary>Read-only projection of <c>Enterprise.Platform.Infrastructure.Persistence.App.Entities.PlatformOutboxMessage</c>.</summary>
/// <remarks>Generated by DtoGen from the entity declaration plus its base-class chain. Edit the entity (or run the generator with an updated config) to change this DTO's shape.</remarks>
public sealed record PlatformOutboxMessageDto(
    string EventType,
    string Payload,
    DateTimeOffset OccurredAt,
    DateTimeOffset? PublishedAt,
    int AttemptCount,
    DateTimeOffset NextAttemptAt,
    string? LastError,
    string? CorrelationId,
    string? TraceId,
    Guid Id);
