// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.AuditLogs"/>. Navigation properties omitted.</summary>
public sealed record AuditLogsDto
{
    public int Id { get; init; }
    public int? UserId { get; init; }
    public string? Username { get; init; }
    public string Action { get; init; } = string.Empty;
    public string? ResourceType { get; init; }
    public string? ResourceId { get; init; }
    public string? Details { get; init; }
    public string? IpAddress { get; init; }
    public string? UserAgent { get; init; }
    public DateTime CreatedAt { get; init; }
    public string? Signature { get; init; }
}
