// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.ChatMessages"/>. Navigation properties omitted.</summary>
public sealed record ChatMessagesDto
{
    public Guid Id { get; init; }
    public Guid ChatSessionId { get; init; }
    public string SenderId { get; init; } = string.Empty;
    public string MessageText { get; init; } = string.Empty;
    public string? AttachmentUrl { get; init; }
    public DateTime SentAt { get; init; }
    public bool IsRead { get; init; }
    public DateTime CreatedAt { get; init; }
    public int CreatedBy { get; init; }
    public DateTime UpdatedAt { get; init; }
    public int UpdatedBy { get; init; }
    public byte[] RowVersion { get; init; } = [];
    public DateTime? DeletedAt { get; init; }
    public int? DeletedBy { get; init; }
}
