// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.GarmentMeasurementMaps"/>. Navigation properties omitted.</summary>
public sealed record GarmentMeasurementMapsDto
{
    public string GarmentTypeCode { get; init; } = string.Empty;
    public Guid MeasurementAttributeId { get; init; }
}
