// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.OrderMilestones"/>. Navigation properties omitted.</summary>
public sealed record OrderMilestonesDto
{
    public Guid Id { get; init; }
    public Guid OrderId { get; init; }
    public string Name { get; init; } = string.Empty;
    public decimal Percentage { get; init; }
    public decimal AmountDue { get; init; }
    public string AmountDueCurrency { get; init; } = string.Empty;
    public decimal AmountPaid { get; init; }
    public string AmountPaidCurrency { get; init; } = string.Empty;
    public string StatusCode { get; init; } = string.Empty;
    public DateTime? DueDate { get; init; }
    public DateTime CreatedAt { get; init; }
    public int CreatedBy { get; init; }
    public DateTime UpdatedAt { get; init; }
    public int UpdatedBy { get; init; }
    public byte[] RowVersion { get; init; } = [];
    public DateTime? DeletedAt { get; init; }
    public int? DeletedBy { get; init; }
}
