// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.Orders"/>. Navigation properties omitted.</summary>
public sealed record OrdersDto
{
    public Guid Id { get; init; }
    public Guid CustomerProfileId { get; init; }
    public Guid? OccasionEventId { get; init; }
    public decimal TotalAmount { get; init; }
    public string TotalCurrency { get; init; } = string.Empty;
    public string StatusCode { get; init; } = string.Empty;
    public string? Notes { get; init; }
    public DateTime CreatedAt { get; init; }
    public int CreatedBy { get; init; }
    public DateTime UpdatedAt { get; init; }
    public int UpdatedBy { get; init; }
    public byte[] RowVersion { get; init; } = [];
    public DateTime? DeletedAt { get; init; }
    public int? DeletedBy { get; init; }
}
