// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.OtpEntries"/>. Navigation properties omitted.</summary>
public sealed record OtpEntriesDto
{
    public int Id { get; init; }
    public string PhoneNumber { get; init; } = string.Empty;
    public string CodeHash { get; init; } = string.Empty;
    public DateTime CreatedAt { get; init; }
    public DateTime ExpiresAt { get; init; }
    public bool IsUsed { get; init; }
    public DateTime? UsedAt { get; init; }
    public int AttemptCount { get; init; }
}
