// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.ProductionRequestStageLogs"/>. Navigation properties omitted.</summary>
public sealed record ProductionRequestStageLogsDto
{
    public Guid Id { get; init; }
    public Guid ProductionRequestId { get; init; }
    public string StageCode { get; init; } = string.Empty;
    public DateTime CompletedAt { get; init; }
    public string? LoggedByAuthUserId { get; init; }
    public DateTime CreatedAt { get; init; }
    public int CreatedBy { get; init; }
    public DateTime UpdatedAt { get; init; }
    public int UpdatedBy { get; init; }
    public byte[] RowVersion { get; init; } = [];
    public DateTime? DeletedAt { get; init; }
    public int? DeletedBy { get; init; }
}
