// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.ProductionRequests"/>. Navigation properties omitted.</summary>
public sealed record ProductionRequestsDto
{
    public Guid Id { get; init; }
    public Guid FamilyMemberId { get; init; }
    public Guid? EventId { get; init; }
    public Guid? FulfillmentOrderId { get; init; }
    public string GarmentTypeCode { get; init; } = string.Empty;
    public string CurrentStatusCode { get; init; } = string.Empty;
    public DateTime TargetDate { get; init; }
    public string? FabricDetails { get; init; }
    public string? DesignNotes { get; init; }
    public string? AssignedWorkerId { get; init; }
    public DateTime CreatedAt { get; init; }
    public int CreatedBy { get; init; }
    public DateTime UpdatedAt { get; init; }
    public int UpdatedBy { get; init; }
    public byte[] RowVersion { get; init; } = [];
    public DateTime? DeletedAt { get; init; }
    public int? DeletedBy { get; init; }
}
