// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.RefreshTokens"/>. Navigation properties omitted.</summary>
public sealed record RefreshTokensDto
{
    public int Id { get; init; }
    public int UserId { get; init; }
    public string Token { get; init; } = string.Empty;
    public DateTime CreatedAt { get; init; }
    public DateTime ExpiresAt { get; init; }
    public bool IsRevoked { get; init; }
    public DateTime? RevokedAt { get; init; }
    public string? RevokedReason { get; init; }
    public string? ReplacedByToken { get; init; }
    public bool IsUsed { get; init; }
    public DateTime? UsedAt { get; init; }
    public string IpAddress { get; init; } = string.Empty;
    public string? UserAgent { get; init; }
    public string? ClientId { get; init; }
    public string? Platform { get; init; }
    public Guid TokenFamilyId { get; init; }
}
