// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.RolePermissions"/>. Navigation properties omitted.</summary>
public sealed record RolePermissionsDto
{
    public int Id { get; init; }
    public int RoleId { get; init; }
    public int PermissionId { get; init; }
    public DateTime GrantedAt { get; init; }
    public int GrantedBy { get; init; }
}
