// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.Roles"/>. Navigation properties omitted.</summary>
public sealed record RolesDto
{
    public int Id { get; init; }
    public string Name { get; init; } = string.Empty;
    public string Description { get; init; } = string.Empty;
    public bool IsActive { get; init; }
    public int Priority { get; init; }
    public DateTime CreatedAt { get; init; }
    public int CreatedBy { get; init; }
    public DateTime UpdatedAt { get; init; }
    public int UpdatedBy { get; init; }
    public byte[] RowVersion { get; init; } = [];
    public DateTime? DeletedAt { get; init; }
    public int? DeletedBy { get; init; }
}
