// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.ScreenMappings"/>. Navigation properties omitted.</summary>
public sealed record ScreenMappingsDto
{
    public Guid Id { get; init; }
    public int RoleId { get; init; }
    public string ScreenKey { get; init; } = string.Empty;
    public bool IsVisible { get; init; }
    public int SortOrder { get; init; }
}
