// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.Sessions"/>. Navigation properties omitted.</summary>
public sealed record SessionsDto
{
    public int Id { get; init; }
    public int UserId { get; init; }
    public string SessionToken { get; init; } = string.Empty;
    public string IpAddress { get; init; } = string.Empty;
    public string? UserAgent { get; init; }
    public string? DeviceInfo { get; init; }
    public DateTime CreatedAt { get; init; }
    public DateTime LastActivityAt { get; init; }
    public DateTime ExpiresAt { get; init; }
    public bool IsActive { get; init; }
    public DateTime? TerminatedAt { get; init; }
    public string? TerminationReason { get; init; }
    public string? ClientId { get; init; }
    public string? Platform { get; init; }
}
