// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.SystemCodes"/>. Navigation properties omitted.</summary>
public sealed record SystemCodesDto
{
    public Guid Id { get; init; }
    public Guid CategoryId { get; init; }
    public string Code { get; init; } = string.Empty;
    public string DisplayValue { get; init; } = string.Empty;
    public int SortOrder { get; init; }
    public bool IsActive { get; init; }
}
