// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.UserPasswordHistory"/>. Navigation properties omitted.</summary>
public sealed record UserPasswordHistoryDto
{
    public int Id { get; init; }
    public int UserId { get; init; }
    public string PasswordHash { get; init; } = string.Empty;
    public DateTime CreatedAt { get; init; }
}
