// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.Users"/>. Navigation properties omitted.</summary>
public sealed record UsersDto
{
    public int Id { get; init; }
    public string Username { get; init; } = string.Empty;
    public string Email { get; init; } = string.Empty;
    public string PasswordHash { get; init; } = string.Empty;
    public string FirstName { get; init; } = string.Empty;
    public string LastName { get; init; } = string.Empty;
    public string? PhoneNumber { get; init; }
    public bool IsEmailVerified { get; init; }
    public string? EmailVerificationToken { get; init; }
    public DateTime? EmailVerificationTokenExpiry { get; init; }
    public string? PasswordResetToken { get; init; }
    public DateTime? PasswordResetTokenExpiry { get; init; }
    public bool IsActive { get; init; }
    public bool IsLocked { get; init; }
    public DateTime? LockedUntil { get; init; }
    public int FailedLoginAttempts { get; init; }
    public DateTime? LastLoginAt { get; init; }
    public string? LastLoginIp { get; init; }
    public bool IsTwoFactorEnabled { get; init; }
    public string? TwoFactorSecret { get; init; }
    public DateTime CreatedAt { get; init; }
    public int CreatedBy { get; init; }
    public DateTime UpdatedAt { get; init; }
    public int UpdatedBy { get; init; }
    public byte[] RowVersion { get; init; } = [];
    public DateTime? DeletedAt { get; init; }
    public int? DeletedBy { get; init; }
}
