// <auto-generated>
// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —
// changes will be overwritten on the next generator run.
// </auto-generated>
#nullable enable

namespace Enterprise.Platform.Contracts.DTOs.EventShopper;

/// <summary>DTO projection of <see cref="global::Enterprise.Platform.Infrastructure.Persistence.EventShopper.Entities.VehicleLocations"/>. Navigation properties omitted.</summary>
public sealed record VehicleLocationsDto
{
    public Guid Id { get; init; }
    public Guid AppointmentId { get; init; }
    public float Latitude { get; init; }
    public float Longitude { get; init; }
    public float? Heading { get; init; }
    public float? SpeedKmh { get; init; }
    public int? EstimatedArrivalMinutes { get; init; }
    public DateTime LastUpdatedAt { get; init; }
    public bool IsActive { get; init; }
    public DateTime CreatedAt { get; init; }
    public int CreatedBy { get; init; }
    public DateTime UpdatedAt { get; init; }
    public int UpdatedBy { get; init; }
    public byte[] RowVersion { get; init; } = [];
    public DateTime? DeletedAt { get; init; }
    public int? DeletedBy { get; init; }
}
