/**
 * ─── shared/layout/sub-nav — type system ────────────────────────────────────────
 *
 * Types for the components rendered between the navbar and the main content:
 *   - Breadcrumb (auto-generated from router data)
 *   - PageHeader (title + actions surface above each page's content)
 *
 * Domain-agnostic. Every visible behaviour is driven by typed config — no
 * component reads page state, route params, or business data directly.
 */

/** A single breadcrumb crumb. The trail is generated by BreadcrumbService from router data. */
export interface BreadcrumbItem {
  /** Stable identifier — used as @for track key. */
  readonly id: string;
  /** Visible label. */
  readonly label: string;
  /** Route to navigate to on click. Omit on the LAST item (current page). */
  readonly routePath?: readonly string[] | string;
  /** Optional PrimeIcons class (`pi pi-home` etc.) rendered before the label. */
  readonly icon?: string;
}

/** Severity-style for the page-header inline badge. */
export type PageHeaderBadgeVariant =
  | 'success'
  | 'warning'
  | 'danger'
  | 'info'
  | 'neutral';

/** A single action button rendered in the page-header right cluster. */
export interface PageHeaderAction {
  /** Visible label. */
  readonly label: string;
  /** Optional PrimeIcons class. */
  readonly icon?: string;
  /**
   * Stable key emitted via `(action)` on the page-header. The host page handles
   * the actual side-effect — page-header owns zero business logic.
   */
  readonly actionKey: string;
  /** Disabled state (e.g. permission gating, form invalid). */
  readonly disabled?: boolean;
  /** Loading state for the primary action — shows a spinner + disables the button. */
  readonly loading?: boolean;
  /** Optional native button type — defaults to 'button'. */
  readonly type?: 'button' | 'submit' | 'reset';
  /**
   * AND-semantics permission gate. When set, the page-header HIDES the
   * action if `AuthStore.hasAllPermissions(...)` returns false. Hide-not-
   * disable so a user who isn't authorized doesn't even discover the
   * action exists (defense-in-depth — the route guard is the primary
   * enforcement; this is the visible-UX layer).
   */
  readonly requiredPermissions?: readonly string[];
}

/** Page-header configuration. Either provided via route data or set dynamically via PageHeaderService. */
export interface PageHeaderConfig {
  /** Page title — rendered as the SINGLE <h1> on the page (WCAG 2.4.6). */
  readonly title: string;
  /** Optional subtitle below the title. */
  readonly subtitle?: string;
  /** Optional icon (PrimeIcons class) rendered left of the title. */
  readonly icon?: string;
  /** Inline badge after the title. Useful for status pills (Active / Draft / Archived). */
  readonly badge?: {
    readonly label: string;
    readonly variant: PageHeaderBadgeVariant;
  };
  /** Primary CTA — right-aligned on desktop, full-width below title on mobile. */
  readonly primaryAction?: PageHeaderAction;
  /** Secondary actions — rendered in a row left of the primary action. */
  readonly secondaryActions?: readonly PageHeaderAction[];
  /** If set, shows a back link above the title. */
  readonly backRoute?: readonly string[] | string;
  /** Optional help tooltip — shown as a `?` icon next to the title with a tooltip. */
  readonly helpTooltip?: string;
}
