namespace Enterprise.Platform.DtoGen.Writing;

/// <summary>
/// Common header inserted at the top of every emitted file. The
/// <c>&lt;auto-generated&gt;</c> tag is a Roslyn convention — the analyzer
/// pipeline downgrades or skips a number of style/quality rules for files
/// carrying this comment, which keeps generated DTOs clean against the
/// project's <c>TreatWarningsAsErrors</c> + <c>latest-recommended</c>
/// analyzer set without per-rule suppression.
/// </summary>
internal static class AutoGeneratedBanner
{
    public const string Text = """
        // <auto-generated>
        //     This file was emitted by tools/Enterprise.Platform.DtoGen.
        //     Do not edit by hand — changes will be overwritten on the next regen.
        //     For custom mapping logic, add a sibling partial in the same namespace.
        // </auto-generated>
        #nullable enable
        """;
}
