using System.Text;
using Enterprise.Platform.DtoGen.Models;

namespace Enterprise.Platform.DtoGen.Writing;

/// <summary>
/// Emits a flat <c>public sealed record &lt;Entity&gt;Dto(...)</c> with one
/// positional parameter per (filtered) entity property. Records give us value
/// equality, immutability, init-only setters, and concise emission — all
/// useful for read-only DTOs.
/// </summary>
internal static class DtoEmitter
{
    public static string Emit(EntityDescriptor entity, string dtoNamespace)
    {
        ArgumentNullException.ThrowIfNull(entity);
        ArgumentException.ThrowIfNullOrWhiteSpace(dtoNamespace);

        var sb = new StringBuilder();
        sb.AppendLine(AutoGeneratedBanner.Text);
        sb.AppendLine();
        sb.Append("namespace ").Append(dtoNamespace).AppendLine(";");
        sb.AppendLine();

        // XML doc on the record — the SCAFFOLD STUB note is intentional: the DTO
        // shape tracks the entity, so engineers reading the DTO know to look at
        // the entity for the source of truth.
        sb.Append("/// <summary>Read-only projection of <c>").Append(entity.Namespace)
          .Append('.').Append(entity.ClassName).AppendLine("</c>.</summary>");
        sb.Append("/// <remarks>Generated by DtoGen from the entity declaration plus its base-class chain. ")
          .AppendLine("Edit the entity (or run the generator with an updated config) to change this DTO's shape.</remarks>");

        sb.Append("public sealed record ").Append(entity.ClassName).AppendLine("Dto(");

        var properties = entity.Properties;
        for (var i = 0; i < properties.Count; i++)
        {
            var p = properties[i];
            sb.Append("    ").Append(p.TypeText).Append(' ').Append(p.Name);
            if (i < properties.Count - 1)
            {
                sb.Append(',');
            }
            else
            {
                sb.Append(");");
            }
            sb.AppendLine();
        }

        return sb.ToString();
    }
}
