using System.Text;
using Enterprise.Platform.DtoGen.Models;

namespace Enterprise.Platform.DtoGen.Writing;

/// <summary>
/// Emits the <c>&lt;Entity&gt;Mappers</c> static partial class — one
/// <c>ToDto</c> extension method per entity, plus a <c>partial void
/// CustomizeToDto</c> hook that hand-authored sibling partials can override
/// for any property whose default property-by-name mapping is wrong.
/// </summary>
/// <remarks>
/// Why an extension method (not an instance method on the entity)? The entity
/// lives in Infrastructure; the DTO + mapper live in Contracts; Infrastructure
/// references Contracts but not vice-versa. Extension methods let the consumer
/// project (Application) say <c>user.ToDto()</c> as if it were intrinsic
/// without violating the layering.
/// </remarks>
internal static class MapperEmitter
{
    public static string Emit(
        EntityDescriptor entity,
        string entityNamespace,
        string dtoNamespace,
        string mapperNamespace)
    {
        ArgumentNullException.ThrowIfNull(entity);
        ArgumentException.ThrowIfNullOrWhiteSpace(entityNamespace);
        ArgumentException.ThrowIfNullOrWhiteSpace(dtoNamespace);
        ArgumentException.ThrowIfNullOrWhiteSpace(mapperNamespace);

        var sb = new StringBuilder();
        sb.AppendLine(AutoGeneratedBanner.Text);
        sb.AppendLine();
        sb.Append("using ").Append(entityNamespace).AppendLine(";");
        sb.Append("using ").Append(dtoNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("namespace ").Append(mapperNamespace).AppendLine(";");
        sb.AppendLine();

        sb.Append("/// <summary>Mappers for the <c>").Append(entity.ClassName).AppendLine("</c> aggregate.</summary>");
        sb.Append("public static partial class ").Append(entity.ClassName).AppendLine("Mappers");
        sb.AppendLine("{");

        // ── ToDto ──────────────────────────────────────────────────────────
        sb.Append("    /// <summary>Projects a <see cref=\"")
          .Append(entity.ClassName)
          .Append("\"/> onto its <see cref=\"")
          .Append(entity.ClassName)
          .AppendLine("Dto\"/> shape.</summary>");
        sb.Append("    /// <remarks>Property names match 1:1 between entity and DTO. ")
          .AppendLine("Override individual properties via the <c>CustomizeToDto</c> partial hook.</remarks>");
        sb.Append("    public static ").Append(entity.ClassName).Append("Dto ToDto(this ").Append(entity.ClassName).AppendLine(" source)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(source);");
        sb.Append("        var dto = new ").Append(entity.ClassName).AppendLine("Dto(");
        var properties = entity.Properties;
        for (var i = 0; i < properties.Count; i++)
        {
            var p = properties[i];
            sb.Append("            ").Append(p.Name).Append(": source.").Append(p.Name);
            if (i < properties.Count - 1)
            {
                sb.Append(',');
            }
            else
            {
                sb.Append(");");
            }
            sb.AppendLine();
        }
        sb.AppendLine("        CustomizeToDto(source, ref dto);");
        sb.AppendLine("        return dto;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ── CustomizeToDto hook ────────────────────────────────────────────
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Hook for hand-authored partials. Implement in a sibling .cs file in the");
        sb.AppendLine("    /// same namespace to tweak the generated mapping for a single property:");
        sb.AppendLine("    /// <code>");
        sb.AppendLine("    /// public static partial class " + entity.ClassName + "Mappers");
        sb.AppendLine("    /// {");
        sb.AppendLine("    ///     static partial void CustomizeToDto(" + entity.ClassName + " src, ref " + entity.ClassName + "Dto dest)");
        sb.AppendLine("    ///         => dest = dest with { /* your override here */ };");
        sb.AppendLine("    /// }");
        sb.AppendLine("    /// </code>");
        sb.AppendLine("    /// When no partial is supplied, the call compiles to a no-op (zero overhead).");
        sb.AppendLine("    /// </summary>");
        sb.Append("    static partial void CustomizeToDto(").Append(entity.ClassName).Append(" source, ref ").Append(entity.ClassName).AppendLine("Dto dto);");

        sb.AppendLine("}");

        return sb.ToString();
    }
}
