using System.Text;
using Enterprise.Platform.DtoGen.Models;

namespace Enterprise.Platform.DtoGen.Writing;

/// <summary>
/// Emits <c>&lt;Db&gt;MappingRegistry.cs</c>: a <see cref="Microsoft.Extensions.DependencyInjection.IServiceCollection"/>
/// extension that registers an <see cref="Enterprise.Platform.Contracts.Abstractions.Mapping.IMapper"/>
/// covering every entity ↔ DTO pair this database scaffolds. Composition root
/// just calls <c>services.AddAppMappers()</c> — no manual list to maintain.
/// </summary>
internal static class RegistryEmitter
{
    public static string Emit(
        IReadOnlyList<EntityDescriptor> entities,
        string databaseName,
        string entityNamespace,
        string dtoNamespace,
        string mapperNamespace)
    {
        ArgumentNullException.ThrowIfNull(entities);
        ArgumentException.ThrowIfNullOrWhiteSpace(databaseName);
        ArgumentException.ThrowIfNullOrWhiteSpace(entityNamespace);
        ArgumentException.ThrowIfNullOrWhiteSpace(dtoNamespace);
        ArgumentException.ThrowIfNullOrWhiteSpace(mapperNamespace);

        var registryName = databaseName + "MappingRegistry";
        var extensionName = "Add" + databaseName + "Mappers";

        var sb = new StringBuilder();
        sb.AppendLine(AutoGeneratedBanner.Text);
        sb.AppendLine();
        sb.Append("using ").Append(entityNamespace).AppendLine(";");
        sb.Append("using ").Append(dtoNamespace).AppendLine(";");
        sb.AppendLine("using Enterprise.Platform.Contracts.Abstractions.Mapping;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.Append("namespace ").Append(mapperNamespace).AppendLine(";");
        sb.AppendLine();

        sb.Append("/// <summary>DI wiring for the <c>").Append(databaseName).AppendLine("</c> database's generated mappers.</summary>");
        sb.Append("public static class ").Append(registryName).AppendLine();
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>");
        sb.Append("    /// Registers an <see cref=\"IMapper\"/> covering every <c>").Append(databaseName)
          .AppendLine("</c> entity ↔ DTO pair (one per scaffolded entity).");
        sb.AppendLine("    /// Idempotent — safe to call from multiple composition roots; only the first registration sticks.");
        sb.AppendLine("    /// </summary>");
        sb.Append("    public static IServiceCollection ").Append(extensionName).AppendLine("(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(services);");
        sb.AppendLine();
        sb.AppendLine("        var registry = new MapperRegistry();");
        foreach (var entity in entities)
        {
            sb.Append("        registry.Register<").Append(entity.ClassName).Append(", ").Append(entity.ClassName)
              .Append("Dto>(").Append(entity.ClassName).Append("Mappers.ToDto);").AppendLine();
        }
        sb.AppendLine();
        sb.AppendLine("        // TryAdd so a host that wires multiple databases doesn't replace");
        sb.AppendLine("        // the first IMapper with the second's narrower coverage.");
        sb.AppendLine("        services.TryAddSingleton<IMapper>(_ => registry.Build());");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
