// <auto-generated>
//     This file was emitted by tools/Enterprise.Platform.DtoGen.
//     Do not edit by hand — changes will be overwritten on the next regen.
//     For custom mapping logic, add a sibling partial in the same namespace.
// </auto-generated>
#nullable enable

using Enterprise.Platform.Infrastructure.Persistence.App.Entities;
using Enterprise.Platform.Contracts.DTOs.App;
using Enterprise.Platform.Contracts.Abstractions.Mapping;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace Enterprise.Platform.Infrastructure.Persistence.App.Mappings;

/// <summary>DI wiring for the <c>App</c> database's generated mappers.</summary>
public static class AppMappingRegistry
{
    /// <summary>
    /// Registers an <see cref="IMapper"/> covering every <c>App</c> entity ↔ DTO pair (one per scaffolded entity).
    /// Idempotent — safe to call from multiple composition roots; only the first registration sticks.
    /// </summary>
    public static IServiceCollection AddAppMappers(this IServiceCollection services)
    {
        ArgumentNullException.ThrowIfNull(services);

        var registry = new MapperRegistry();
        registry.Register<PlatformOutboxMessage, PlatformOutboxMessageDto>(PlatformOutboxMessageMappers.ToDto);
        registry.Register<User, UserDto>(UserMappers.ToDto);

        // TryAdd so a host that wires multiple databases doesn't replace
        // the first IMapper with the second's narrower coverage.
        services.TryAddSingleton<IMapper>(_ => registry.Build());
        return services;
    }
}
