// <auto-generated>
//     This file was emitted by tools/Enterprise.Platform.DtoGen.
//     Do not edit by hand — changes will be overwritten on the next regen.
//     For custom mapping logic, add a sibling partial in the same namespace.
// </auto-generated>
#nullable enable

using Enterprise.Platform.Infrastructure.Persistence.App.Entities;
using Enterprise.Platform.Contracts.DTOs.App;

namespace Enterprise.Platform.Infrastructure.Persistence.App.Mappings;

/// <summary>Mappers for the <c>PlatformOutboxMessage</c> aggregate.</summary>
public static partial class PlatformOutboxMessageMappers
{
    /// <summary>Projects a <see cref="PlatformOutboxMessage"/> onto its <see cref="PlatformOutboxMessageDto"/> shape.</summary>
    /// <remarks>Property names match 1:1 between entity and DTO. Override individual properties via the <c>CustomizeToDto</c> partial hook.</remarks>
    public static PlatformOutboxMessageDto ToDto(this PlatformOutboxMessage source)
    {
        ArgumentNullException.ThrowIfNull(source);
        var dto = new PlatformOutboxMessageDto(
            EventType: source.EventType,
            Payload: source.Payload,
            OccurredAt: source.OccurredAt,
            PublishedAt: source.PublishedAt,
            AttemptCount: source.AttemptCount,
            NextAttemptAt: source.NextAttemptAt,
            LastError: source.LastError,
            CorrelationId: source.CorrelationId,
            TraceId: source.TraceId,
            Id: source.Id);
        CustomizeToDto(source, ref dto);
        return dto;
    }

    /// <summary>
    /// Hook for hand-authored partials. Implement in a sibling .cs file in the
    /// same namespace to tweak the generated mapping for a single property:
    /// <code>
    /// public static partial class PlatformOutboxMessageMappers
    /// {
    ///     static partial void CustomizeToDto(PlatformOutboxMessage src, ref PlatformOutboxMessageDto dest)
    ///         => dest = dest with { /* your override here */ };
    /// }
    /// </code>
    /// When no partial is supplied, the call compiles to a no-op (zero overhead).
    /// </summary>
    static partial void CustomizeToDto(PlatformOutboxMessage source, ref PlatformOutboxMessageDto dto);
}
