// <auto-generated>
//     This file was emitted by tools/Enterprise.Platform.DtoGen.
//     Do not edit by hand — changes will be overwritten on the next regen.
//     For custom mapping logic, add a sibling partial in the same namespace.
// </auto-generated>
#nullable enable

using Enterprise.Platform.Infrastructure.Persistence.App.Entities;
using Enterprise.Platform.Contracts.DTOs.App;

namespace Enterprise.Platform.Infrastructure.Persistence.App.Mappings;

/// <summary>Mappers for the <c>User</c> aggregate.</summary>
public static partial class UserMappers
{
    /// <summary>Projects a <see cref="User"/> onto its <see cref="UserDto"/> shape.</summary>
    /// <remarks>Property names match 1:1 between entity and DTO. Override individual properties via the <c>CustomizeToDto</c> partial hook.</remarks>
    public static UserDto ToDto(this User source)
    {
        ArgumentNullException.ThrowIfNull(source);
        var dto = new UserDto(
            Email: source.Email,
            FirstName: source.FirstName,
            LastName: source.LastName,
            ExternalIdentityId: source.ExternalIdentityId,
            IsActive: source.IsActive,
            LastLoginAt: source.LastLoginAt,
            IsDeleted: source.IsDeleted,
            DeletedAt: source.DeletedAt,
            DeletedBy: source.DeletedBy,
            CreatedBy: source.CreatedBy,
            CreatedAt: source.CreatedAt,
            ModifiedBy: source.ModifiedBy,
            ModifiedAt: source.ModifiedAt,
            Id: source.Id);
        CustomizeToDto(source, ref dto);
        return dto;
    }

    /// <summary>
    /// Hook for hand-authored partials. Implement in a sibling .cs file in the
    /// same namespace to tweak the generated mapping for a single property:
    /// <code>
    /// public static partial class UserMappers
    /// {
    ///     static partial void CustomizeToDto(User src, ref UserDto dest)
    ///         => dest = dest with { /* your override here */ };
    /// }
    /// </code>
    /// When no partial is supplied, the call compiles to a no-op (zero overhead).
    /// </summary>
    static partial void CustomizeToDto(User source, ref UserDto dto);
}
