using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Enterprise.Platform.DtoGen;

/// <summary>
/// Reads EF-scaffolded entity files and emits two matched outputs per entity:
/// a flat DTO record in <c>Contracts/DTOs/&lt;DbName&gt;/</c> and a Mapster
/// <c>IRegister</c> class containing <c>TypeAdapterConfig</c> calls for every
/// entity/DTO pair. Idempotent — re-runs after every re-scaffold.
/// </summary>
internal sealed class Generator
{
    private const string AutoGeneratedBanner =
        "// <auto-generated>\n" +
        "// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —\n" +
        "// changes will be overwritten on the next generator run.\n" +
        "// </auto-generated>\n" +
        "#nullable enable\n";

    /// <summary>Runs the generator with the resolved <paramref name="options"/>.</summary>
    public static async Task<int> RunAsync(GeneratorOptions options, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(options);

        if (!Directory.Exists(options.EntitiesDirectory))
        {
            Console.Error.WriteLine($"error: entities directory not found: {options.EntitiesDirectory}");
            return 3;
        }

        var entityFiles = Directory
            .EnumerateFiles(options.EntitiesDirectory, "*.cs", SearchOption.TopDirectoryOnly)
            .OrderBy(f => f, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        if (entityFiles.Length == 0)
        {
            Console.Error.WriteLine($"error: no .cs files found under {options.EntitiesDirectory}");
            return 4;
        }

        // Pass 1 — inventory entity class names so we can skip navigation properties
        // whose type is another entity class.
        var entities = new List<EntityInfo>(entityFiles.Length);
        foreach (var file in entityFiles)
        {
            var info = await ParseEntityAsync(file, cancellationToken).ConfigureAwait(false);
            if (info is not null)
            {
                entities.Add(info);
            }
        }

        if (entities.Count == 0)
        {
            Console.Error.WriteLine("error: no entity classes discovered in the supplied directory.");
            return 5;
        }

        var entityNames = entities.Select(e => e.ClassName).ToHashSet(StringComparer.Ordinal);

        // Pass 2 — emit
        if (options.DryRun)
        {
            Console.WriteLine("DRY RUN — files that would be written:");
            foreach (var entity in entities)
            {
                Console.WriteLine($"  DTO     : {Path.Combine(options.DtoOutputDirectory, entity.ClassName + "Dto.cs")}");
            }

            Console.WriteLine($"  mapping : {Path.Combine(options.MappingOutputDirectory, DeriveRegistryFileName(options) + ".cs")}");
            return 0;
        }

        Directory.CreateDirectory(options.DtoOutputDirectory);
        Directory.CreateDirectory(options.MappingOutputDirectory);

        foreach (var entity in entities)
        {
            var dtoPath = Path.Combine(options.DtoOutputDirectory, entity.ClassName + "Dto.cs");
            await File.WriteAllTextAsync(dtoPath, RenderDto(entity, entityNames, options.DtoNamespace), cancellationToken)
                .ConfigureAwait(false);
        }

        var registryName = DeriveRegistryFileName(options);
        var registryPath = Path.Combine(options.MappingOutputDirectory, registryName + ".cs");
        await File.WriteAllTextAsync(registryPath, RenderRegistry(entities, options, registryName), cancellationToken)
            .ConfigureAwait(false);

        var repoFilesWritten = 0;
        if (options.RepositoryScaffold is { } repoOptions)
        {
            foreach (var entity in entities)
            {
                repoFilesWritten += await ScaffoldRepositoryAsync(entity, repoOptions, options, cancellationToken).ConfigureAwait(false);
            }
        }

        Console.WriteLine(
            $"DtoGen: wrote {entities.Count} DTO file(s), 1 mapping registry ({registryName}){(repoFilesWritten > 0 ? $", and {repoFilesWritten} repository skeleton file(s)" : "")}.");
        return 0;
    }

    private static async Task<int> ScaffoldRepositoryAsync(
        EntityInfo entity,
        RepositoryScaffoldOptions repoOptions,
        GeneratorOptions rootOptions,
        CancellationToken cancellationToken)
    {
        var appDir = Path.Combine(repoOptions.ApplicationOutputRoot, "Features", repoOptions.DbName, entity.ClassName, "Repositories");
        var infraDir = Path.Combine(repoOptions.InfrastructureOutputRoot, "Persistence", repoOptions.DbName, "Repositories");
        Directory.CreateDirectory(appDir);
        Directory.CreateDirectory(infraDir);

        var appPath = Path.Combine(appDir, $"I{entity.ClassName}Repository.cs");
        var infraPath = Path.Combine(infraDir, $"{entity.ClassName}Repository.cs");

        var written = 0;

        if (repoOptions.Force || !File.Exists(appPath))
        {
            var interfaceSource = RenderRepositoryInterface(entity, repoOptions, rootOptions);
            await File.WriteAllTextAsync(appPath, interfaceSource, cancellationToken).ConfigureAwait(false);
            written++;
        }

        if (repoOptions.Force || !File.Exists(infraPath))
        {
            var implSource = RenderRepositoryImplementation(entity, repoOptions, rootOptions);
            await File.WriteAllTextAsync(infraPath, implSource, cancellationToken).ConfigureAwait(false);
            written++;
        }

        return written;
    }

    private static string RenderRepositoryInterface(
        EntityInfo entity,
        RepositoryScaffoldOptions repoOptions,
        GeneratorOptions rootOptions)
    {
        var appNs = $"{repoOptions.ApplicationNamespaceRoot}.Features.{repoOptions.DbName}.{entity.ClassName}.Repositories";
        var idProperty = entity.Properties.FirstOrDefault(p => p.Name == "Id");
        var idType = idProperty?.TypeText ?? "int";

        var sb = new StringBuilder();
        sb.Append(AutoGeneratedBanner);
        sb.AppendLine();
        sb.Append("using ").Append(rootOptions.DtoNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("namespace ").Append(appNs).AppendLine(";");
        sb.AppendLine();
        sb.Append("/// <summary>Per-aggregate repository contract for <c>").Append(entity.ClassName).AppendLine("</c>. Returns DTOs (never entities).</summary>");
        sb.Append("public interface I").Append(entity.ClassName).AppendLine("Repository");
        sb.AppendLine("{");
        sb.Append("    /// <summary>Returns a page of ").Append(entity.ClassName).AppendLine(" rows. TODO: add per-aggregate filters.</summary>");
        sb.Append("    Task<IReadOnlyList<").Append(entity.ClassName).AppendLine("Dto>> ListAsync(int skip, int take, CancellationToken cancellationToken = default);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Counts matching rows. Paired with <see cref=\"ListAsync\"/> for pagination.</summary>");
        sb.AppendLine("    Task<int> CountAsync(CancellationToken cancellationToken = default);");
        sb.AppendLine();
        sb.Append("    /// <summary>Returns the ").Append(entity.ClassName).AppendLine(" with <paramref name=\"id\"/>, or <c>null</c> when absent.</summary>");
        sb.Append("    Task<").Append(entity.ClassName).Append("Dto?> GetByIdAsync(").Append(idType).AppendLine(" id, CancellationToken cancellationToken = default);");
        sb.AppendLine();
        sb.AppendLine("    // TODO: add aggregate-specific reads (e.g. NameExistsAsync, FindByExternalId).");
        sb.AppendLine("    // TODO: add CreateAsync / UpdateAsync / DeleteAsync with appropriate input records.");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string RenderRepositoryImplementation(
        EntityInfo entity,
        RepositoryScaffoldOptions repoOptions,
        GeneratorOptions rootOptions)
    {
        var appNs = $"{repoOptions.ApplicationNamespaceRoot}.Features.{repoOptions.DbName}.{entity.ClassName}.Repositories";
        var infraNs = $"{repoOptions.InfrastructureNamespaceRoot}.Persistence.{repoOptions.DbName}.Repositories";
        var contextType = $"{repoOptions.DbName}DbContext";
        var hasDeletedAt = entity.Properties.Any(p => p.Name == "DeletedAt");

        var sb = new StringBuilder();
        sb.Append(AutoGeneratedBanner);
        sb.AppendLine();
        sb.Append("using ").Append(appNs).AppendLine(";");
        sb.Append("using ").Append(rootOptions.DtoNamespace).AppendLine(";");
        sb.Append("using ").Append(entity.Namespace).AppendLine(";");
        sb.Append("using ").Append(repoOptions.InfrastructureNamespaceRoot).Append(".Persistence.").Append(repoOptions.DbName).AppendLine(".Contexts;");
        sb.AppendLine("using Mapster;");
        sb.AppendLine("using MapsterMapper;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.Append("namespace ").Append(infraNs).AppendLine(";");
        sb.AppendLine();
        sb.Append("/// <summary>EF-backed <c>I").Append(entity.ClassName).AppendLine("Repository</c> skeleton — extend with aggregate-specific methods.</summary>");
        sb.Append("public sealed class ").Append(entity.ClassName).Append("Repository(")
            .Append(contextType).Append(" context, IMapper mapper) : I").Append(entity.ClassName).AppendLine("Repository");
        sb.AppendLine("{");
        sb.Append("    private readonly ").Append(contextType).AppendLine(" _context = context ?? throw new ArgumentNullException(nameof(context));");
        sb.AppendLine("    private readonly IMapper _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.Append("    public Task<IReadOnlyList<").Append(entity.ClassName).AppendLine("Dto>> ListAsync(int skip, int take, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.Append("        var query = _context.").Append(entity.ClassName).AppendLine(".AsNoTracking()");
        if (hasDeletedAt)
        {
            sb.AppendLine("            .Where(e => e.DeletedAt == null)");
        }
        sb.AppendLine("            .OrderBy(e => e.Id)");
        sb.AppendLine("            .Skip(skip)");
        sb.AppendLine("            .Take(take);");
        sb.AppendLine();
        sb.Append("        return query.ProjectToType<").Append(entity.ClassName).AppendLine("Dto>(_mapper.Config).ToListAsync(cancellationToken)");
        sb.Append("            .ContinueWith(t => (IReadOnlyList<").Append(entity.ClassName).AppendLine("Dto>)t.Result, cancellationToken);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.Append("    public Task<int> CountAsync(CancellationToken cancellationToken = default) => _context.").Append(entity.ClassName);
        if (hasDeletedAt)
        {
            sb.Append(".Where(e => e.DeletedAt == null)");
        }

        sb.AppendLine(".CountAsync(cancellationToken);");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        var idProperty = entity.Properties.FirstOrDefault(p => p.Name == "Id");
        var idType = idProperty?.TypeText ?? "int";
        sb.Append("    public async Task<").Append(entity.ClassName).Append("Dto?> GetByIdAsync(").Append(idType).AppendLine(" id, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.Append("        var entity = await _context.").Append(entity.ClassName).AppendLine(".AsNoTracking()");
        sb.Append("            .FirstOrDefaultAsync(e => e.Id == id");
        if (hasDeletedAt)
        {
            sb.Append(" && e.DeletedAt == null");
        }

        sb.AppendLine(", cancellationToken).ConfigureAwait(false);");
        sb.Append("        return entity is null ? null : _mapper.Map<").Append(entity.ClassName).AppendLine("Dto>(entity);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // TODO: implement aggregate-specific reads + CreateAsync / UpdateAsync / DeleteAsync.");
        sb.AppendLine("    // Canonical example: Application/Features/EventShopper/Roles/* + Infrastructure/Persistence/EventShopper/Repositories/RolesRepository.cs");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static async Task<EntityInfo?> ParseEntityAsync(string filePath, CancellationToken cancellationToken)
    {
        var source = await File.ReadAllTextAsync(filePath, cancellationToken).ConfigureAwait(false);
        var tree = CSharpSyntaxTree.ParseText(source, cancellationToken: cancellationToken);
        var root = (CompilationUnitSyntax)await tree.GetRootAsync(cancellationToken).ConfigureAwait(false);

        var classDecl = root.DescendantNodes().OfType<ClassDeclarationSyntax>().FirstOrDefault();
        if (classDecl is null)
        {
            return null;
        }

        var namespaceDecl = root.DescendantNodes().OfType<BaseNamespaceDeclarationSyntax>().FirstOrDefault();

        var properties = classDecl.Members
            .OfType<PropertyDeclarationSyntax>()
            .Where(p => p.Modifiers.Any(m => m.IsKind(SyntaxKind.PublicKeyword)))
            .Select(p => new PropertyInfo(
                Name: p.Identifier.ValueText,
                TypeText: p.Type.ToString(),
                IsVirtual: p.Modifiers.Any(m => m.IsKind(SyntaxKind.VirtualKeyword))))
            .ToList();

        return new EntityInfo(
            ClassName: classDecl.Identifier.ValueText,
            Namespace: namespaceDecl?.Name.ToString() ?? string.Empty,
            Properties: properties);
    }

    private static string RenderDto(
        EntityInfo entity,
        HashSet<string> entityNames,
        string dtoNamespace)
    {
        var sb = new StringBuilder();
        sb.Append(AutoGeneratedBanner);
        sb.AppendLine();
        sb.Append("namespace ").Append(dtoNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("/// <summary>DTO projection of <see cref=\"global::")
            .Append(entity.Namespace)
            .Append('.')
            .Append(entity.ClassName)
            .AppendLine("\"/>. Navigation properties omitted.</summary>");
        sb.Append("public sealed record ").Append(entity.ClassName).AppendLine("Dto");
        sb.AppendLine("{");

        foreach (var property in entity.Properties)
        {
            if (IsSkippableNavigation(property, entityNames))
            {
                continue;
            }

            var defaultInit = DefaultInitializer(property.TypeText);
            sb.Append("    public ")
                .Append(property.TypeText)
                .Append(' ')
                .Append(property.Name)
                .Append(" { get; init; }");

            if (defaultInit is not null)
            {
                sb.Append(" = ").Append(defaultInit).Append(';');
            }

            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string RenderRegistry(
        IReadOnlyList<EntityInfo> entities,
        GeneratorOptions options,
        string registryName)
    {
        var sb = new StringBuilder();
        sb.Append(AutoGeneratedBanner);
        sb.AppendLine();
        sb.Append("using ").Append(options.DtoNamespace).AppendLine(";");

        foreach (var ns in entities.Select(e => e.Namespace).Distinct(StringComparer.Ordinal).OrderBy(n => n, StringComparer.Ordinal))
        {
            if (!string.IsNullOrEmpty(ns))
            {
                sb.Append("using ").Append(ns).AppendLine(";");
            }
        }

        sb.AppendLine("using Mapster;");
        sb.AppendLine();
        sb.Append("namespace ").Append(options.MappingNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("/// <summary>Mapster registry auto-generated by DtoGen. One entry per scaffolded entity; bi-directional bindings.</summary>");
        sb.AppendLine();
        sb.Append("public sealed class ").Append(registryName).AppendLine(" : IRegister");
        sb.AppendLine("{");
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public void Register(TypeAdapterConfig config)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(config);");
        sb.AppendLine();
        foreach (var entity in entities.OrderBy(e => e.ClassName, StringComparer.Ordinal))
        {
            sb.Append("        config.NewConfig<")
                .Append(entity.ClassName)
                .Append(", ")
                .Append(entity.ClassName)
                .AppendLine("Dto>();");
            sb.Append("        config.NewConfig<")
                .Append(entity.ClassName)
                .Append("Dto, ")
                .Append(entity.ClassName)
                .AppendLine(">();");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static bool IsSkippableNavigation(PropertyInfo property, HashSet<string> entityNames)
    {
        // Rule 1 — EF scaffold marks navigations as `virtual`.
        if (property.IsVirtual)
        {
            return true;
        }

        // Rule 2 — defensive: even if `virtual` is missing, skip collections of, or direct references to, known entity classes.
        var type = property.TypeText;
        foreach (var name in entityNames)
        {
            if (string.Equals(type, name, StringComparison.Ordinal)
                || type.Contains('<' + name + '>', StringComparison.Ordinal)
                || type.Contains('<' + name + '?', StringComparison.Ordinal)
                || type.EndsWith('?' + name, StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static string? DefaultInitializer(string typeText)
    {
        // Preserve EF scaffold's non-nullable string / byte[] defaults so the generated
        // DTO matches the compiler's nullability expectations.
        if (typeText == "string") return "string.Empty";
        if (typeText == "byte[]") return "[]";
        return null;
    }

    private static string DeriveRegistryFileName(GeneratorOptions options)
    {
        // Use the last namespace segment of the mapping namespace → "Mappings" is common;
        // use the segment just before it instead if present, otherwise "GeneratedMappingRegistry".
        var segments = options.MappingNamespace.Split('.');
        var candidate = segments.Length >= 2 ? segments[^2] : "Generated";
        return candidate + "MappingRegistry";
    }

    private sealed record EntityInfo(
        string ClassName,
        string Namespace,
        IReadOnlyList<PropertyInfo> Properties);

    private sealed record PropertyInfo(string Name, string TypeText, bool IsVirtual);
}

/// <summary>Resolved CLI options.</summary>
internal sealed record GeneratorOptions(
    string EntitiesDirectory,
    string DtoOutputDirectory,
    string MappingOutputDirectory,
    string DtoNamespace,
    string MappingNamespace,
    bool DryRun,
    bool Force,
    RepositoryScaffoldOptions? RepositoryScaffold = null);

/// <summary>
/// When populated, the generator additionally emits per-entity repository stubs —
/// a canonical starting point for a DB-first aggregate's feature slice. Writes are
/// **non-overwriting by default** so hand-edits survive re-runs; pass <c>Force=true</c>
/// to regenerate.
/// </summary>
internal sealed record RepositoryScaffoldOptions(
    string ApplicationOutputRoot,
    string InfrastructureOutputRoot,
    string ApplicationNamespaceRoot,
    string InfrastructureNamespaceRoot,
    string DbName,
    bool Force);
