using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Enterprise.Platform.DtoGen;

/// <summary>
/// Reads EF-scaffolded entity files and emits two matched outputs per entity:
/// a flat DTO record in <c>Contracts/DTOs/&lt;DbName&gt;/</c> and a Mapster
/// <c>IRegister</c> class containing <c>TypeAdapterConfig</c> calls for every
/// entity/DTO pair. Idempotent — re-runs after every re-scaffold.
/// </summary>
internal sealed class Generator
{
    private const string AutoGeneratedBanner =
        "// <auto-generated>\n" +
        "// This file is emitted by tools/Enterprise.Platform.DtoGen. DO NOT EDIT BY HAND —\n" +
        "// changes will be overwritten on the next generator run.\n" +
        "// </auto-generated>\n" +
        "#nullable enable\n";

    /// <summary>Runs the generator with the resolved <paramref name="options"/>.</summary>
    public static async Task<int> RunAsync(GeneratorOptions options, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(options);

        if (!Directory.Exists(options.EntitiesDirectory))
        {
            Console.Error.WriteLine($"error: entities directory not found: {options.EntitiesDirectory}");
            return 3;
        }

        var entityFiles = Directory
            .EnumerateFiles(options.EntitiesDirectory, "*.cs", SearchOption.TopDirectoryOnly)
            .OrderBy(f => f, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        if (entityFiles.Length == 0)
        {
            Console.Error.WriteLine($"error: no .cs files found under {options.EntitiesDirectory}");
            return 4;
        }

        // Pass 1 — inventory entity class names so we can skip navigation properties
        // whose type is another entity class.
        var entities = new List<EntityInfo>(entityFiles.Length);
        foreach (var file in entityFiles)
        {
            var info = await ParseEntityAsync(file, cancellationToken).ConfigureAwait(false);
            if (info is not null)
            {
                entities.Add(info);
            }
        }

        if (entities.Count == 0)
        {
            Console.Error.WriteLine("error: no entity classes discovered in the supplied directory.");
            return 5;
        }

        var entityNames = entities.Select(e => e.ClassName).ToHashSet(StringComparer.Ordinal);

        // Pass 2 — emit
        if (options.DryRun)
        {
            Console.WriteLine("DRY RUN — files that would be written:");
            foreach (var entity in entities)
            {
                Console.WriteLine($"  DTO     : {Path.Combine(options.DtoOutputDirectory, entity.ClassName + "Dto.cs")}");
            }

            Console.WriteLine($"  mapping : {Path.Combine(options.MappingOutputDirectory, DeriveRegistryFileName(options) + ".cs")}");
            return 0;
        }

        Directory.CreateDirectory(options.DtoOutputDirectory);
        Directory.CreateDirectory(options.MappingOutputDirectory);

        foreach (var entity in entities)
        {
            var dtoPath = Path.Combine(options.DtoOutputDirectory, entity.ClassName + "Dto.cs");
            await File.WriteAllTextAsync(dtoPath, RenderDto(entity, entityNames, options.DtoNamespace), cancellationToken)
                .ConfigureAwait(false);
        }

        var registryName = DeriveRegistryFileName(options);
        var registryPath = Path.Combine(options.MappingOutputDirectory, registryName + ".cs");
        await File.WriteAllTextAsync(registryPath, RenderRegistry(entities, options, registryName), cancellationToken)
            .ConfigureAwait(false);

        Console.WriteLine(
            $"DtoGen: wrote {entities.Count} DTO file(s) and 1 mapping registry ({registryName}).");
        return 0;
    }

    private static async Task<EntityInfo?> ParseEntityAsync(string filePath, CancellationToken cancellationToken)
    {
        var source = await File.ReadAllTextAsync(filePath, cancellationToken).ConfigureAwait(false);
        var tree = CSharpSyntaxTree.ParseText(source, cancellationToken: cancellationToken);
        var root = (CompilationUnitSyntax)await tree.GetRootAsync(cancellationToken).ConfigureAwait(false);

        var classDecl = root.DescendantNodes().OfType<ClassDeclarationSyntax>().FirstOrDefault();
        if (classDecl is null)
        {
            return null;
        }

        var namespaceDecl = root.DescendantNodes().OfType<BaseNamespaceDeclarationSyntax>().FirstOrDefault();

        var properties = classDecl.Members
            .OfType<PropertyDeclarationSyntax>()
            .Where(p => p.Modifiers.Any(m => m.IsKind(SyntaxKind.PublicKeyword)))
            .Select(p => new PropertyInfo(
                Name: p.Identifier.ValueText,
                TypeText: p.Type.ToString(),
                IsVirtual: p.Modifiers.Any(m => m.IsKind(SyntaxKind.VirtualKeyword))))
            .ToList();

        return new EntityInfo(
            ClassName: classDecl.Identifier.ValueText,
            Namespace: namespaceDecl?.Name.ToString() ?? string.Empty,
            Properties: properties);
    }

    private static string RenderDto(
        EntityInfo entity,
        HashSet<string> entityNames,
        string dtoNamespace)
    {
        var sb = new StringBuilder();
        sb.Append(AutoGeneratedBanner);
        sb.AppendLine();
        sb.Append("namespace ").Append(dtoNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("/// <summary>DTO projection of <see cref=\"global::")
            .Append(entity.Namespace)
            .Append('.')
            .Append(entity.ClassName)
            .AppendLine("\"/>. Navigation properties omitted.</summary>");
        sb.Append("public sealed record ").Append(entity.ClassName).AppendLine("Dto");
        sb.AppendLine("{");

        foreach (var property in entity.Properties)
        {
            if (IsSkippableNavigation(property, entityNames))
            {
                continue;
            }

            var defaultInit = DefaultInitializer(property.TypeText);
            sb.Append("    public ")
                .Append(property.TypeText)
                .Append(' ')
                .Append(property.Name)
                .Append(" { get; init; }");

            if (defaultInit is not null)
            {
                sb.Append(" = ").Append(defaultInit).Append(';');
            }

            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string RenderRegistry(
        IReadOnlyList<EntityInfo> entities,
        GeneratorOptions options,
        string registryName)
    {
        var sb = new StringBuilder();
        sb.Append(AutoGeneratedBanner);
        sb.AppendLine();
        sb.Append("using ").Append(options.DtoNamespace).AppendLine(";");

        foreach (var ns in entities.Select(e => e.Namespace).Distinct(StringComparer.Ordinal).OrderBy(n => n, StringComparer.Ordinal))
        {
            if (!string.IsNullOrEmpty(ns))
            {
                sb.Append("using ").Append(ns).AppendLine(";");
            }
        }

        sb.AppendLine("using Mapster;");
        sb.AppendLine();
        sb.Append("namespace ").Append(options.MappingNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("/// <summary>Mapster registry auto-generated by DtoGen. One entry per scaffolded entity; bi-directional bindings.</summary>");
        sb.AppendLine();
        sb.Append("public sealed class ").Append(registryName).AppendLine(" : IRegister");
        sb.AppendLine("{");
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public void Register(TypeAdapterConfig config)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(config);");
        sb.AppendLine();
        foreach (var entity in entities.OrderBy(e => e.ClassName, StringComparer.Ordinal))
        {
            sb.Append("        config.NewConfig<")
                .Append(entity.ClassName)
                .Append(", ")
                .Append(entity.ClassName)
                .AppendLine("Dto>();");
            sb.Append("        config.NewConfig<")
                .Append(entity.ClassName)
                .Append("Dto, ")
                .Append(entity.ClassName)
                .AppendLine(">();");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static bool IsSkippableNavigation(PropertyInfo property, HashSet<string> entityNames)
    {
        // Rule 1 — EF scaffold marks navigations as `virtual`.
        if (property.IsVirtual)
        {
            return true;
        }

        // Rule 2 — defensive: even if `virtual` is missing, skip collections of, or direct references to, known entity classes.
        var type = property.TypeText;
        foreach (var name in entityNames)
        {
            if (string.Equals(type, name, StringComparison.Ordinal)
                || type.Contains('<' + name + '>', StringComparison.Ordinal)
                || type.Contains('<' + name + '?', StringComparison.Ordinal)
                || type.EndsWith('?' + name, StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static string? DefaultInitializer(string typeText)
    {
        // Preserve EF scaffold's non-nullable string / byte[] defaults so the generated
        // DTO matches the compiler's nullability expectations.
        if (typeText == "string") return "string.Empty";
        if (typeText == "byte[]") return "[]";
        return null;
    }

    private static string DeriveRegistryFileName(GeneratorOptions options)
    {
        // Use the last namespace segment of the mapping namespace → "Mappings" is common;
        // use the segment just before it instead if present, otherwise "GeneratedMappingRegistry".
        var segments = options.MappingNamespace.Split('.');
        var candidate = segments.Length >= 2 ? segments[^2] : "Generated";
        return candidate + "MappingRegistry";
    }

    private sealed record EntityInfo(
        string ClassName,
        string Namespace,
        IReadOnlyList<PropertyInfo> Properties);

    private sealed record PropertyInfo(string Name, string TypeText, bool IsVirtual);
}

/// <summary>Resolved CLI options.</summary>
internal sealed record GeneratorOptions(
    string EntitiesDirectory,
    string DtoOutputDirectory,
    string MappingOutputDirectory,
    string DtoNamespace,
    string MappingNamespace,
    bool DryRun,
    bool Force);
